package de.unisaarland.cs.st.pirates.group1.sim.util;

public enum Register {
	SENSE_CELLTYPE,
	SENSE_SUPPLY,
	SENSE_TREASURE,
	SENSE_MARKER0,
	SENSE_MARKER1,
	SENSE_MARKER2,
	SENSE_MARKER3,
	SENSE_MARKER4,
	SENSE_MARKER5,
	SENSE_ENEMYMARKER,
	SENSE_SHIPTYPE,
	SENSE_SHIPDIRECTION,
	SENSE_SHIPLOADED,
	SENSE_SHIPCONDITION,
	SHIP_DIRECTION,
	SHIP_LOAD,
	SHIP_MORAL,
	SHIP_CONDITION;
}
